-- ALIADOS FANTASMA
-- Hotfix: eliminación definitiva sin bloqueo, confirmación por nombre y motivo opcional.
-- Ejecutar completo en Supabase > SQL Editor.

create table if not exists public.auditoria_administrativa (
  id bigint generated by default as identity primary key,
  actor_id uuid,
  accion text not null,
  entidad text not null,
  entidad_id uuid,
  nombre_entidad text,
  motivo text,
  metadata jsonb not null default '{}'::jsonb,
  creado_en timestamptz not null default now()
);

alter table public.auditoria_administrativa enable row level security;

create or replace function public.admin_eliminar_negocio_definitivo(
  p_negocio_id uuid,
  p_nombre_confirmacion text,
  p_motivo text default null
)
returns void
language plpgsql
security definer
set search_path = public
set statement_timeout = '15s'
as $$
declare
  v_nombre text;
begin
  if auth.uid() is null or not public.es_administrador() then
    raise exception 'Acceso no autorizado';
  end if;

  select nombre
    into v_nombre
  from public.negocios
  where id = p_negocio_id
  for update;

  if v_nombre is null then
    raise exception 'El negocio no existe o ya fue eliminado';
  end if;

  if btrim(coalesce(p_nombre_confirmacion, '')) <> btrim(v_nombre) then
    raise exception 'El nombre de confirmación no coincide exactamente';
  end if;

  insert into public.auditoria_administrativa (
    actor_id,
    accion,
    entidad,
    entidad_id,
    nombre_entidad,
    motivo
  ) values (
    auth.uid(),
    'eliminacion_definitiva',
    'negocio',
    p_negocio_id,
    v_nombre,
    nullif(btrim(coalesce(p_motivo, '')), '')
  );

  -- Las migraciones actuales definen ON DELETE CASCADE o SET NULL para las
  -- relaciones del negocio. Eliminar desde la tabla principal evita bloqueos
  -- causados por borrados manuales incompletos o en un orden incorrecto.
  delete from public.negocios
  where id = p_negocio_id;

  if not found then
    raise exception 'No fue posible eliminar el negocio';
  end if;
end;
$$;

revoke all on function public.admin_eliminar_negocio_definitivo(uuid, text, text) from public;
grant execute on function public.admin_eliminar_negocio_definitivo(uuid, text, text) to authenticated;

-- Elimina la firma anterior para evitar que el navegador llame accidentalmente
-- a una versión obsoleta de la función.
drop function if exists public.admin_eliminar_negocio_definitivo(uuid);
