-- Aliados Fantasma · privacidad, oportunidades seguras y analítica · 2026-08-31
-- YA APLICADO en producción. Este archivo queda como respaldo/reproducibilidad.
create table if not exists public.contact_access_log (
  id bigint generated by default as identity primary key,
  necesidad_id uuid not null references public.necesidades(id) on delete cascade,
  negocio_id uuid not null references public.negocios(id) on delete cascade,
  user_id uuid references auth.users(id) on delete set null,
  action text not null default 'respuesta_y_contacto',
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists contact_access_need_idx on public.contact_access_log(necesidad_id,created_at desc);
create index if not exists contact_access_business_idx on public.contact_access_log(negocio_id,created_at desc);
alter table public.contact_access_log enable row level security;

create or replace function public.af_publicar_necesidad_v2(
  p_categoria_id uuid,p_categoria_texto text,p_nombre_cliente text,p_whatsapp text,p_titulo text,p_descripcion text,p_estado_region text,p_municipio text,
  p_colonia text default null,p_presupuesto_min numeric default null,p_presupuesto_max numeric default null,p_fecha_necesaria date default null,p_urgencia text default 'normal',p_acepta_compartir_contacto boolean default false
) returns table(id uuid,tracking_token uuid,expires_at timestamptz)
language plpgsql security definer set search_path='' as $$
begin
  if coalesce(p_acepta_compartir_contacto,false) is not true then raise exception 'Debes autorizar compartir tu contacto con negocios que respondan a tu solicitud'; end if;
  return query select * from public.af_publicar_necesidad(p_categoria_id,p_categoria_texto,p_nombre_cliente,p_whatsapp,p_titulo,p_descripcion,p_estado_region,p_municipio,p_colonia,p_presupuesto_min,p_presupuesto_max,p_fecha_necesaria,p_urgencia);
end; $$;
revoke all on function public.af_publicar_necesidad_v2(uuid,text,text,text,text,text,text,text,text,numeric,numeric,date,text,boolean) from public;
grant execute on function public.af_publicar_necesidad_v2(uuid,text,text,text,text,text,text,text,text,numeric,numeric,date,text,boolean) to anon,authenticated,service_role;

create or replace function public.af_oportunidades_para_negocio(p_negocio uuid)
returns table(id uuid,categoria_id uuid,categoria_texto text,titulo text,descripcion text,estado_region text,municipio text,colonia text,presupuesto_min numeric,presupuesto_max numeric,fecha_necesaria date,urgencia text,created_at timestamptz,match_id uuid,score integer,ola smallint,razones jsonb,estado_match text,visto_at timestamptz,respondido_at timestamptz,turno_expires_at timestamptz,estado_turno text,ya_respondio boolean,respuesta_id uuid,precio_estimado numeric,tiempo_estimado text,mensaje text)
language sql stable security definer set search_path='' as $$
  select n.id,n.categoria_id,n.categoria_texto,n.titulo,n.descripcion,n.estado_region,n.municipio,n.colonia,n.presupuesto_min,n.presupuesto_max,n.fecha_necesaria,n.urgencia,n.created_at,
         m.id,m.score,m.ola,m.razones,m.estado,m.visto_at,m.respondido_at,m.turno_expires_at,m.turno_estado,
         (r.id is not null),r.id,r.precio_estimado,r.tiempo_estimado,r.mensaje
  from public.matches_necesidad m join public.necesidades n on n.id=m.necesidad_id
  left join public.respuestas_necesidad r on r.necesidad_id=n.id and r.negocio_id=p_negocio and r.estado in ('contactado','cerrada')
  where m.negocio_id=p_negocio and (select af_private.af_puede_gestionar_negocio((select auth.uid()),p_negocio)) and n.estado='abierta' and n.expires_at>now() and m.turno_estado in ('activo','aceptado')
  order by case when m.turno_estado='activo' then 0 else 1 end,m.score desc,n.created_at desc;
$$;
revoke all on function public.af_oportunidades_para_negocio(uuid) from public;
grant execute on function public.af_oportunidades_para_negocio(uuid) to authenticated,service_role;

create or replace function public.af_responder_y_contactar(p_necesidad uuid,p_negocio uuid,p_precio numeric default null,p_tiempo text default null,p_mensaje text default null)
returns table(nombre_cliente text,whatsapp text)
language plpgsql security definer set search_path='' as $$
declare v_uid uuid:=(select auth.uid()); v_need public.necesidades%rowtype;
begin
  if v_uid is null or not af_private.af_puede_gestionar_negocio(v_uid,p_negocio) then raise exception 'No autorizado'; end if;
  select * into v_need from public.necesidades where id=p_necesidad for update;
  if not found or v_need.estado<>'abierta' or v_need.expires_at<=now() then raise exception 'La solicitud ya no está disponible'; end if;
  if coalesce(v_need.acepta_compartir_contacto,false) is not true then raise exception 'El cliente no autorizó compartir su contacto'; end if;
  perform public.af_responder_solicitud(p_necesidad,p_negocio,p_precio,p_tiempo,p_mensaje);
  insert into public.contact_access_log(necesidad_id,negocio_id,user_id,action,metadata) values(p_necesidad,p_negocio,v_uid,'respuesta_y_contacto',jsonb_build_object('channel','whatsapp'));
  return query select v_need.nombre_cliente,v_need.whatsapp;
end; $$;
revoke all on function public.af_responder_y_contactar(uuid,uuid,numeric,text,text) from public;
grant execute on function public.af_responder_y_contactar(uuid,uuid,numeric,text,text) to authenticated,service_role;

create or replace function public.af_growth_summary(p_days integer default 30)
returns jsonb language plpgsql security definer set search_path='' as $$
declare v_from timestamptz:=now()-make_interval(days=>greatest(1,least(365,p_days))); v_result jsonb;
begin
  if not public.es_administrador() then raise exception 'Acceso administrativo requerido'; end if;
  select jsonb_build_object('days',greatest(1,least(365,p_days)),'needs',count(*),'needs_with_matches',count(*) filter(where matches_count>0),'needs_with_responses',count(*) filter(where respuestas_count>0),'resolved',count(*) filter(where estado='resuelta' or resuelta_at is not null),'without_coverage',count(*) filter(where coalesce(sin_cobertura,false)),'avg_matches',coalesce(round(avg(matches_count)::numeric,2),0),'avg_responses',coalesce(round(avg(respuestas_count)::numeric,2),0),'top_demands',coalesce((select jsonb_agg(x order by x.n desc) from (select categoria_texto categoria,count(*)::integer n from public.necesidades where created_at>=v_from group by categoria_texto order by count(*) desc limit 10)x),'[]'::jsonb),'top_queries',coalesce((select jsonb_agg(x order by x.n desc) from (select left(lower(trim(titulo)),80) query,count(*)::integer n from public.necesidades where created_at>=v_from group by left(lower(trim(titulo)),80) order by count(*) desc limit 10)x),'[]'::jsonb),'contacts_opened',(select count(*) from public.contact_access_log where created_at>=v_from)) into v_result from public.necesidades where created_at>=v_from;
  return v_result;
end; $$;
revoke all on function public.af_growth_summary(integer) from public;
grant execute on function public.af_growth_summary(integer) to authenticated,service_role;
