import { supabase } from './supabase-client.js?v=20260831-GROWTH1';
const LAUNCH_AT=new Date('2026-08-24T11:00:00-06:00');
const postLaunch=Date.now()>=LAUNCH_AT.getTime();
function setMeta(selector,content){const el=document.querySelector(selector);if(el)el.setAttribute('content',content)}
async function track(tipo,metadata={}){try{if(!supabase)return;await supabase.rpc('registrar_evento_directorio',{p_tipo:'vista_directorio',p_negocio_id:null,p_consulta:null,p_metadata:{event:tipo,...metadata,path:location.pathname}})}catch{}}
function installGrowthStrip(){if(document.querySelector('.af-growth-strip'))return;const strip=document.createElement('section');strip.className='af-growth-strip';strip.setAttribute('aria-label','Cómo funciona Aliados Fantasma');strip.innerHTML=`<article class="af-growth-step"><b>1</b><div><strong>Dinos qué necesitas</strong><small>Producto, servicio, zona y urgencia.</small></div></article><article class="af-growth-step"><b>2</b><div><strong>MATCH busca opciones</strong><small>Compara tu solicitud con negocios compatibles.</small></div></article><article class="af-growth-step"><b>3</b><div><strong>Recibe propuestas</strong><small>Tu WhatsApp solo se revela a un negocio cuando responde.</small></div></article>`;const header=document.querySelector('.site-header');header?.after(strip);}
function moveNeedFirst(){const need=document.querySelector('#lo-necesito');const strip=document.querySelector('.af-growth-strip');if(need&&strip&&strip.nextElementSibling!==need)strip.after(need);document.querySelector('.need-promo-section')?.setAttribute('hidden','');}
function activatePostLaunch(){document.documentElement.classList.add('af-postlaunch');document.body.classList.add('af-postlaunch');document.title='Aliados Fantasma | Encuentra negocios que pueden ayudarte';setMeta('meta[name="description"]','Dinos qué necesitas y Aliados Fantasma encuentra negocios compatibles para ayudarte. Explora negocios locales, publica una solicitud y recibe propuestas.');setMeta('meta[property="og:title"]','Aliados Fantasma | Dinos qué necesitas');setMeta('meta[property="og:description"]','MATCH conecta solicitudes reales con negocios compatibles. Publica lo que necesitas y recibe opciones sin buscar uno por uno.');const badge=document.querySelector('#launch-badge-primary');if(badge)badge.innerHTML='<i></i> Red local activa';document.querySelectorAll('.pre2-hero-copy h1').forEach(h=>{if(/lanz|prepar|antes/i.test(h.textContent||''))h.innerHTML='Encuentra negocios que <span>sí pueden ayudarte.</span>'});const closing=document.querySelector('.pre2-closing');if(closing)closing.hidden=true;}
function bindTracking(){document.addEventListener('click',e=>{const a=e.target.closest('a,button');if(!a)return;if(a.closest('#lo-necesito'))track('need_interaction',{action:(a.id||a.textContent||'').trim().slice(0,60)});else if(a.matches('[href*="registro"]'))track('registration_click');else if(a.matches('[href*="explorar"]'))track('directory_click');});const form=document.querySelector('#home-need-form');form?.addEventListener('submit',()=>track('need_submit_start'));}
function focusFromHash(){if(location.hash==='#lo-necesito'){setTimeout(()=>document.querySelector('#home-need-form-panel')?.classList.add('af-growth-focus'),250)}}
if(postLaunch)activatePostLaunch();installGrowthStrip();moveNeedFirst();bindTracking();focusFromHash();track('home_view',{post_launch:postLaunch});if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('/af-sw.js?v=20260831-PWA2',{scope:'/'}).catch(()=>{}));
