import { supabase } from './supabase-client.js?v=20260720-600';
import { SUPABASE_URL } from './config.js?v=20260717-2';
const $=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const money=v=>new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN'}).format(Number(v||0));const num=v=>new Intl.NumberFormat('es-MX',{maximumFractionDigits:2}).format(Number(v||0));
const token=new URLSearchParams(location.search).get('t');let card;let toastTimer;
function toast(text,type='ok'){const e=$('#rw-toast');e.textContent=text;e.className=`rw-toast ${type==='error'?'error':''}`;e.hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>e.hidden=true,6000)}
function qr(el,text){
  el.innerHTML='';
  if(!token){el.innerHTML='<span class="rw-qr-error">QR no disponible</span>';return;}
  const img=document.createElement('img');
  img.alt='Código QR de tu tarjeta Rewards';img.width=180;img.height=180;img.loading='eager';img.decoding='async';
  img.src=`${SUPABASE_URL}/functions/v1/rewards-qr?token=${encodeURIComponent(token)}&size=220`;
  img.onerror=()=>{el.innerHTML='<span class="rw-qr-error">No se pudo cargar el QR. Actualiza la tarjeta.</span>';};
  el.appendChild(img);
}
function condition(r){if(r.condicion_tipo==='sellos')return `${num(r.condicion_valor)} sellos`;if(r.condicion_tipo==='puntos')return `${num(r.condicion_valor)} puntos`;if(r.condicion_tipo==='cashback')return money(r.condicion_valor);return 'Beneficio especial';}
async function load(){if(!token){$('#customer-card').innerHTML='<div class="rw-card"><div class="rw-empty">Esta tarjeta no tiene un código válido.</div></div>';return;}const {data,error}=await supabase.rpc('rewards_tarjeta_publica',{p_token:token});if(error||!data){$('#customer-card').innerHTML='<div class="rw-card"><div class="rw-empty">La tarjeta no existe o ya no está activa.</div></div>';return;}card=data;render();}
function render(){const n=card.negocio,p=card.programa,s=card.saldo,rews=card.recompensas||[];document.title=`${p.nombre} | Aliados Rewards`;$('#customer-card').innerHTML=`<article class="customer-card"><div class="customer-brand">${n.logo_url?`<img src="${esc(n.logo_url)}" alt="">`:`<img src="aliados-fantasma-icono.png" alt="">`}<div><p class="rw-kicker">${p.modo_prueba?'MODO PRUEBA · ':''}TARJETA DIGITAL</p><h1>${esc(p.nombre)}</h1><p>${esc(card.cliente_nombre)}</p></div></div><div class="customer-balance"><div class="rw-balance"><small>Sellos</small><strong>${s.sellos}</strong></div><div class="rw-balance"><small>Puntos</small><strong>${num(s.puntos)}</strong></div><div class="rw-balance"><small>Cashback</small><strong>${money(s.cashback)}</strong></div></div><div id="customer-qr" class="rw-qr"></div><p style="text-align:center;color:#a7b4ce;font-size:13px">Presenta este código en ${esc(n.nombre)} para identificar tu tarjeta.</p><div class="customer-wallet"><button class="rw-btn" id="wallet-google">Agregar a Google Wallet</button><button class="rw-btn" id="wallet-apple">Agregar a Apple Wallet</button></div></article><section class="rw-card" style="margin-top:14px"><p class="rw-kicker">TUS RECOMPENSAS</p><h2>Beneficios</h2><div class="customer-rewards">${rews.length?rews.map(r=>`<div class="customer-reward ${r.disponible?'ready':''}"><strong>${r.disponible?'🎁 ':''}${esc(r.titulo)}</strong><p>${esc(r.descripcion||condition(r))}</p><span class="rw-badge ${r.disponible?'green':''}">${r.disponible?'Disponible':`Necesitas ${esc(condition(r))}`}</span></div>`).join(''):'<div class="rw-empty">Este negocio todavía no ha publicado recompensas.</div>'}</div></section>`;setTimeout(()=>qr($('#customer-qr'),location.href),0);$('#wallet-google').onclick=()=>wallet('google');$('#wallet-apple').onclick=()=>wallet('apple');}
async function wallet(provider){const btn=provider==='google'?$('#wallet-google'):$('#wallet-apple'),old=btn.textContent;btn.disabled=true;btn.textContent='Preparando…';try{const res=await fetch(`${SUPABASE_URL}/functions/v1/rewards-wallet`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({provider,token,origin:location.origin})});const ct=res.headers.get('content-type')||'';if(provider==='apple'&&res.ok&&ct.includes('application/vnd.apple.pkpass')){const blob=await res.blob();const url=URL.createObjectURL(blob);location.href=url;setTimeout(()=>URL.revokeObjectURL(url),5000);return;}const data=await res.json().catch(()=>({}));if(!res.ok)throw new Error(data.message||'Wallet aún no está disponible');if(data.url)location.href=data.url;}catch(e){toast(e.message,'error')}finally{btn.disabled=false;btn.textContent=old;}}
$('#refresh-card').onclick=load;addEventListener('visibilitychange',()=>{if(!document.hidden)load()});load();
