import { supabase } from './supabase-client.js?v=20260720-600';
import { getActiveContext, setActiveContext } from './auth-context.js?v=20260724-CTX-LOCK-002';
const grid=document.querySelector('#opp-grid'),loading=document.querySelector('#opp-loading'),empty=document.querySelector('#opp-empty'),summary=document.querySelector('#opp-summary'),businessName=document.querySelector('#need-business-name');
const modal=document.querySelector('#quote-modal'),quoteForm=document.querySelector('#quote-form'),quoteAlert=document.querySelector('#quote-alert');
const bell=document.querySelector('#opp-notification-bell'),bellBadge=document.querySelector('#opp-notification-badge'),bellPanel=document.querySelector('#opp-notification-panel'),bellList=document.querySelector('#opp-notification-list');
const params=new URLSearchParams(location.search);const focusNeed=params.get('need')||'';
let user=null,business=null,memberships=[],items=[],notifications=[],channel=null;
const esc=v=>String(v??'').replace(/[&<>'"]/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[ch]));
const money=v=>v==null||v===''?'':new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN',maximumFractionDigits:0}).format(Number(v));
function relativeTime(v){const m=Math.max(0,Math.floor((Date.now()-new Date(v).getTime())/60000));if(m<1)return'ahora';if(m<60)return`hace ${m} min`;const h=Math.floor(m/60);if(h<24)return`hace ${h} h`;return`hace ${Math.floor(h/24)} d`;}
function urgency(v){return({hoy:'Lo necesita hoy','24_horas':'En 24 horas',esta_semana:'Esta semana',normal:'Sin prisa'})[v]||'Sin prisa';}
function budget(i){if(i.presupuesto_min!=null&&i.presupuesto_max!=null)return`${money(i.presupuesto_min)}–${money(i.presupuesto_max)}`;if(i.presupuesto_max!=null)return`Hasta ${money(i.presupuesto_max)}`;if(i.presupuesto_min!=null)return`Desde ${money(i.presupuesto_min)}`;return'A convenir';}
function remaining(v){if(!v)return'';const min=Math.max(0,Math.ceil((new Date(v).getTime()-Date.now())/60000));return min?`Responde en ~${min} min`:'Asignación por vencer';}
async function requireBusiness(){if(!supabase){location.replace('login.html');return false;}const {data:{user:u}}=await supabase.auth.getUser();if(!u){location.replace(`login.html?return=${encodeURIComponent(location.pathname.split('/').pop()+location.search)}`);return false;}user=u;const {data,error}=await supabase.from('miembros_negocio').select('negocio_id,rol,activo,negocios(id,nombre,slug,activo,estado,estado_operativo)').eq('perfil_id',u.id).eq('activo',true);if(error)throw error;memberships=(data||[]).filter(r=>r.negocios&&r.negocios.activo!==false&&!['suspendido','eliminacion_programada'].includes(r.negocios.estado_operativo));if(!memberships.length){location.replace('panel.html');return false;}const context=getActiveContext(u.id);const preferred=params.get('business')||context?.businessId||localStorage.getItem('af_owner_business_id')||'';const m=memberships.find(r=>r.negocio_id===preferred)||memberships[0];business=m.negocios;localStorage.setItem('af_owner_business_id',business.id);try{setActiveContext(u.id,{type:'owner',businessId:business.id});}catch{}businessName.textContent=business.nombre||'Mi negocio';return true;}
async function load({silent=false}={}){if(!silent){loading.style.display='flex';grid.style.display='none';}const {data,error}=await supabase.rpc('af_solicitudes_para_negocio',{p_negocio:business.id});if(error)throw error;items=data||[];render();}
function card(i){const place=[i.colonia,i.municipio,i.estado_region].filter(Boolean).join(' · ');const urgent=['hoy','24_horas'].includes(i.urgencia);return`<article class="need-card need-opportunity relevant" data-need-id="${esc(i.id)}"><div class="need-opportunity-meta"><span class="need-tag match">✦ RECOMENDADA PARA TU NEGOCIO</span><span class="need-tag">${esc(i.categoria_texto||'Solicitud')}</span><span class="need-tag ${urgent?'hot':''}">${esc(urgency(i.urgencia))}</span></div><div class="need-opportunity-head"><h3>${esc(i.titulo)}</h3><small>${esc(relativeTime(i.created_at))}</small></div><p>${esc(i.descripcion||'')}</p><div class="need-opportunity-details"><span>⌖ <b>${esc(place)}</b></span><span>$ <b>${esc(budget(i))}</b></span></div><div class="privacy-note">🔒 El WhatsApp del cliente está oculto. Si puedes atenderlo, el cliente recibirá tus datos y decidirá si te escribe.</div>${i.estado_turno==='activo'?`<div class="need-opportunity-actions private-actions"><button class="need-button primary" type="button" data-accept="${esc(i.id)}">Sí, puedo atenderlo</button><button class="need-button reject" type="button" data-reject="${esc(i.id)}">No lo manejo</button></div><small class="need-muted">${esc(remaining(i.turno_expires_at))}</small>`:`<div class="private-badge">✓ Opción enviada al cliente</div>`}</article>`;}
function render(){loading.style.display='none';const active=items.filter(i=>i.estado_turno==='activo'),done=items.filter(i=>i.ya_respondio||i.estado_turno==='aceptado');document.querySelector('#stat-matched').textContent=items.length;document.querySelector('#stat-new').textContent=active.length;document.querySelector('#stat-contacted').textContent=done.length;summary.textContent=active.length?`${active.length} solicitud${active.length===1?'':'es'} esperando tu respuesta`:'Sin solicitudes pendientes';grid.innerHTML=items.map(card).join('');grid.style.display=items.length?'':'none';empty.classList.toggle('show',!items.length);document.querySelectorAll('[data-accept]').forEach(b=>b.addEventListener('click',()=>openQuote(b.dataset.accept)));document.querySelectorAll('[data-reject]').forEach(b=>b.addEventListener('click',()=>rejectNeed(b.dataset.reject)));if(focusNeed)setTimeout(()=>document.querySelector(`[data-need-id="${CSS.escape(focusNeed)}"]`)?.scrollIntoView({behavior:'smooth',block:'center'}),80);}
function openQuote(id){const i=items.find(x=>x.id===id);if(!i)return;document.querySelector('#quote-need-id').value=id;document.querySelector('#quote-request').textContent=`${i.titulo} · ${i.municipio}`;document.querySelector('#quote-price').value='';document.querySelector('#quote-time').value='';document.querySelector('#quote-message').value='Sí podemos ayudarte con esta solicitud.';quoteAlert.className='need-alert';quoteAlert.textContent='';modal.classList.add('show');}
function closeQuote(){modal.classList.remove('show');}
async function rejectNeed(id){const btn=document.querySelector(`[data-reject="${CSS.escape(id)}"]`);if(btn){btn.disabled=true;btn.textContent='Pasando al siguiente…';}const {error}=await supabase.rpc('af_rechazar_solicitud',{p_necesidad:id,p_negocio:business.id});if(error){console.error(error);if(btn){btn.disabled=false;btn.textContent='No lo manejo';}return;}await load({silent:true});}
document.querySelector('#quote-close')?.addEventListener('click',closeQuote);document.querySelector('#quote-cancel')?.addEventListener('click',closeQuote);modal?.addEventListener('click',e=>{if(e.target===modal)closeQuote();});
quoteForm?.addEventListener('submit',async e=>{e.preventDefault();const id=document.querySelector('#quote-need-id').value;const priceRaw=document.querySelector('#quote-price').value.trim(),time=document.querySelector('#quote-time').value.trim(),message=document.querySelector('#quote-message').value.trim();const btn=document.querySelector('#quote-submit');btn.disabled=true;btn.textContent='Enviando…';const {error}=await supabase.rpc('af_responder_solicitud',{p_necesidad:id,p_negocio:business.id,p_precio:priceRaw?Number(priceRaw):null,p_tiempo:time||null,p_mensaje:message||null});btn.disabled=false;btn.textContent='Enviar opción al cliente';if(error){console.error(error);quoteAlert.textContent=/asignada a otra/i.test(error.message||'')?'Esta solicitud ya pasó a otra opción.':'No pudimos enviar tu respuesta.';quoteAlert.className='need-alert show error';return;}closeQuote();await load({silent:true});});
function updateBell(){const count=notifications.filter(n=>!n.leida).length;bellBadge.textContent=count>99?'99+':String(count);bellBadge.hidden=count===0;}
function renderNotes(){if(!notifications.length){bellList.innerHTML='<div class="notification-empty"><strong>Sin avisos nuevos</strong><p>Te avisaremos cuando una solicitud sea recomendada para tu negocio.</p></div>';return;}bellList.innerHTML=notifications.slice(0,30).map(n=>`<button class="opp-notification-item ${n.leida?'':'unread'}" type="button" data-note="${esc(n.id)}"><strong>🔔 ${esc(n.titulo)}</strong><p>${esc(n.mensaje)}</p><small>${esc(relativeTime(n.created_at))}</small></button>`).join('');bellList.querySelectorAll('[data-note]').forEach(b=>b.addEventListener('click',()=>openNote(b.dataset.note)));}
async function loadNotes(){const {data,error}=await supabase.from('notificaciones_plataforma').select('id,tipo,titulo,mensaje,leida,created_at,accion_url').eq('usuario_id',user.id).order('created_at',{ascending:false}).limit(40);if(error)throw error;notifications=data||[];renderNotes();updateBell();}
async function openNote(id){const n=notifications.find(x=>x.id===id);if(!n)return;if(!n.leida){await supabase.from('notificaciones_plataforma').update({leida:true,leida_at:new Date().toISOString()}).eq('id',id).eq('usuario_id',user.id);n.leida=true;renderNotes();updateBell();}bellPanel.hidden=true;if(n.accion_url)location.href=n.accion_url;}
bell?.addEventListener('click',()=>bellPanel.hidden=!bellPanel.hidden);document.querySelector('#opp-read-all')?.addEventListener('click',async()=>{await supabase.from('notificaciones_plataforma').update({leida:true,leida_at:new Date().toISOString()}).eq('usuario_id',user.id).eq('leida',false);notifications.forEach(n=>n.leida=true);renderNotes();updateBell();});
async function init(){try{if(!await requireBusiness())return;await Promise.all([load(),loadNotes()]);channel=supabase.channel(`solicitudes-${user.id}`).on('postgres_changes',{event:'INSERT',schema:'public',table:'notificaciones_plataforma',filter:`usuario_id=eq.${user.id}`},async()=>{await Promise.all([loadNotes(),load({silent:true})]);}).subscribe();setInterval(()=>load({silent:true}),30000);}catch(e){console.error(e);loading.textContent='No pudimos cargar las solicitudes.';}}
window.addEventListener('beforeunload',()=>{if(channel)supabase.removeChannel(channel);});init();
