import { supabase } from './supabase-client.js?v=20260720-600';
import { requireContext } from './auth-context.js?v=20260724-CTX-LOCK-002';
import { SUPABASE_URL } from './config.js?v=20260717-2';

const $ = s => document.querySelector(s);
const $$ = s => [...document.querySelectorAll(s)];
const money = v => new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN',maximumFractionDigits:2}).format(Number(v||0));
const num = v => new Intl.NumberFormat('es-MX',{maximumFractionDigits:2}).format(Number(v||0));
const fmtDate = v => v ? new Intl.DateTimeFormat('es-MX',{dateStyle:'medium',timeStyle:'short'}).format(new Date(v)) : '—';
const esc = v => String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
let user, context, business, program;
let rules=[], clients=[], rewards=[], movements=[];
let selectedMembership=null;
let toastTimer;

function toast(text,type='ok',ms=5000){const el=$('#rw-toast');el.textContent=text;el.className=`rw-toast ${type==='error'?'error':''}`;el.hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.hidden=true,ms);}
function openModal(id){const el=$(id);if(el){el.hidden=false;document.documentElement.style.overflow='hidden';}}
function closeModals(){$$('.rw-modal').forEach(x=>x.hidden=true);document.documentElement.style.overflow='';}
$$('[data-close-modal]').forEach(b=>b.onclick=closeModals);
$$('.rw-modal').forEach(m=>m.addEventListener('click',e=>{if(e.target===m)closeModals();}));
addEventListener('keydown',e=>{if(e.key==='Escape')closeModals();});

function activateTab(name){$$('.rw-tab').forEach(b=>b.classList.toggle('active',b.dataset.tab===name));$$('.rw-section').forEach(s=>s.classList.toggle('active',s.dataset.section===name));history.replaceState(null,'',`#${name}`);if(name==='movimientos')loadMovements();if(name==='wallet')renderWalletClient();scrollTo({top:0,behavior:'smooth'});}
$$('.rw-tab').forEach(b=>b.onclick=()=>activateTab(b.dataset.tab));$$('[data-tab-open]').forEach(b=>b.onclick=()=>activateTab(b.dataset.tabOpen));

async function init(){
  if(!supabase){toast('Supabase no está configurado.','error',0);return;}
  const {data:{user:authUser},error}=await supabase.auth.getUser();
  if(error||!authUser){location.replace('login.html');return;}
  user=authUser;context=requireContext(user.id,'owner');if(!context)return;
  const businessId=context.businessId;
  $('#back-panel').href=`panel.html?business=${encodeURIComponent(businessId)}`;
  const {data:member,error:memberError}=await supabase.from('miembros_negocio').select('negocio_id,rol,negocios(id,nombre,slug,logo_url,color_primario,color_secundario)').eq('perfil_id',user.id).eq('negocio_id',businessId).eq('activo',true).maybeSingle();
  if(memberError||!member?.negocios){toast('No tienes acceso a Rewards para este negocio.','error',0);return;}
  business=member.negocios;
  $('#business-pill').textContent=business.nombre;
  const {data:ensured,error:ensureError}=await supabase.rpc('rewards_asegurar_programa',{p_negocio_id:business.id});
  if(ensureError){toast(ensureError.message,'error',0);return;}
  program=ensured;
  await Promise.all([loadRules(),loadClients(),loadRewards(),loadSummary(),checkWalletStatus()]);
  renderProgram();renderRulesSummary();renderClients();renderRewards();
  const hash=location.hash.replace('#','');if(['resumen','clientes','programa','recompensas','movimientos','wallet'].includes(hash))activateTab(hash);
}

async function loadRules(){const {data,error}=await supabase.from('rewards_reglas').select('*').eq('programa_id',program.id).order('prioridad');if(error)throw error;rules=data||[];}
async function loadSummary(){const {data,error}=await supabase.rpc('rewards_resumen_programa',{p_programa_id:program.id});if(error){console.error(error);return;}$('#metric-clients').textContent=num(data.clientes);$('#metric-purchases').textContent=num(data.compras_30d);$('#metric-sales').textContent=money(data.ventas_30d);$('#metric-cashback').textContent=money(data.cashback);$('#program-name-side').textContent=program.nombre;$('#program-status-side').textContent=program.activo?(program.modo_prueba?'Activo en modo prueba. Registra operaciones reales de prueba y revierte si es necesario.':'Programa activo para clientes.'):'Programa pausado. Los saldos se conservan.';$('#test-pill').textContent=program.modo_prueba?'Modo prueba':'Producción';$('#test-pill').className=`rw-pill ${program.modo_prueba?'test':'live'}`;}
function ruleBy(type){return rules.find(r=>r.tipo===type)||{};}
function renderRulesSummary(){const host=$('#rules-summary');const items=[];const s=ruleBy('sellos'),p=ruleBy('puntos'),c=ruleBy('cashback');if(s.activo)items.push(['● Sellos',`${num(s.valor)} por cada ${money(s.monto_base)}`]);if(p.activo)items.push(['★ Puntos',`${num(p.valor)} por cada ${money(p.monto_base)}`]);if(c.activo)items.push(['↩ Cashback',`${num(c.porcentaje)}% de la compra como saldo promocional`]);host.innerHTML=items.length?items.map(([a,b])=>`<div class="rw-list-item"><div class="rw-list-main"><strong>${esc(a)}</strong><small>${esc(b)}</small></div><span class="rw-badge green">Activo</span></div>`).join(''):'<div class="rw-empty">No hay reglas activas. Configura el programa antes de registrar compras.</div>';}
function renderProgram(){const f=$('#program-form');f.program_name.value=program.nombre||`${business.nombre} Rewards`;f.program_active.checked=!!program.activo;f.test_mode.checked=!!program.modo_prueba;const s=ruleBy('sellos'),p=ruleBy('puntos'),c=ruleBy('cashback');$('#rule-stamps').checked=!!s.activo;$('#stamps-base').value=s.monto_base??100;$('#stamps-value').value=s.valor??1;$('#rule-points').checked=!!p.activo;$('#points-base').value=p.monto_base??10;$('#points-value').value=p.valor??1;$('#rule-cashback').checked=!!c.activo;$('#cashback-percent').value=c.porcentaje??3;$('#cashback-min').value=c.compra_minima??0;}
$('#program-form').addEventListener('submit',async e=>{e.preventDefault();const f=e.currentTarget;const payload=[{tipo:'sellos',nombre:`${$('#stamps-value').value||1} sello(s) por cada $${$('#stamps-base').value||100}`,activo:$('#rule-stamps').checked,monto_base:$('#stamps-base').value||100,valor:$('#stamps-value').value||1,compra_minima:0},{tipo:'puntos',nombre:'Puntos por compra',activo:$('#rule-points').checked,monto_base:$('#points-base').value||10,valor:$('#points-value').value||1,compra_minima:0},{tipo:'cashback',nombre:'Cashback promocional',activo:$('#rule-cashback').checked,porcentaje:$('#cashback-percent').value||0,compra_minima:$('#cashback-min').value||0}];const btn=f.querySelector('button[type=submit]');btn.disabled=true;btn.textContent='Guardando…';const {error}=await supabase.rpc('rewards_guardar_configuracion',{p_programa_id:program.id,p_nombre:f.program_name.value,p_activo:f.program_active.checked,p_modo_prueba:f.test_mode.checked,p_reglas:payload});btn.disabled=false;btn.textContent='Guardar configuración';if(error){toast(error.message,'error');return;}const {data}=await supabase.from('rewards_programas').select('*').eq('id',program.id).single();program=data;await loadRules();renderProgram();renderRulesSummary();await loadSummary();toast('Programa Rewards actualizado.');});

async function loadClients(){const {data,error}=await supabase.from('rewards_membresias').select('id,public_token,estado,puntos,sellos,cashback_saldo,nivel,ultima_actividad_at,updated_at,rewards_clientes!inner(id,nombre,telefono,email,activo)').eq('programa_id',program.id).order('ultima_actividad_at',{ascending:false,nullsFirst:false});if(error)throw error;clients=(data||[]).filter(x=>x.rewards_clientes?.activo);}
function filteredClients(){const q=$('#client-search').value.trim().toLowerCase();if(!q)return clients;return clients.filter(x=>[x.rewards_clientes?.nombre,x.rewards_clientes?.telefono,x.rewards_clientes?.email].some(v=>String(v||'').toLowerCase().includes(q)));}
function renderClients(){const rows=filteredClients();const host=$('#clients-list');host.innerHTML=rows.length?rows.map(x=>`<button class="rw-list-item clickable ${selectedMembership?.id===x.id?'selected':''}" data-client="${x.id}" type="button"><div class="rw-list-main"><strong>${esc(x.rewards_clientes.nombre)}</strong><small>${esc(x.rewards_clientes.telefono||x.rewards_clientes.email||'Sin contacto')}</small></div><div class="rw-badges"><span class="rw-badge">${x.sellos} sellos</span><span class="rw-badge">${num(x.puntos)} pts</span></div></button>`).join(''):'<div class="rw-empty">Todavía no hay clientes. Crea el primero para probar Rewards.</div>';host.querySelectorAll('[data-client]').forEach(b=>b.onclick=()=>selectClient(b.dataset.client));}
$('#client-search').addEventListener('input',renderClients);$('#new-client-btn').onclick=()=>openModal('#client-modal');
$('#client-form').addEventListener('submit',async e=>{e.preventDefault();const f=e.currentTarget,btn=f.querySelector('button');btn.disabled=true;btn.textContent='Creando…';const fd=new FormData(f);const {data,error}=await supabase.rpc('rewards_crear_cliente',{p_programa_id:program.id,p_nombre:fd.get('nombre'),p_telefono:fd.get('telefono')||null,p_email:fd.get('email')||null});btn.disabled=false;btn.textContent='Crear cliente y QR';if(error){toast(error.message,'error');return;}f.reset();closeModals();await loadClients();renderClients();await loadSummary();selectClient(data.membresia_id);toast('Cliente creado. Su tarjeta Rewards ya está lista.');});
function publicCardUrl(row){return `${location.origin}${location.pathname.replace(/[^/]+$/,'')}mi-rewards.html?t=${encodeURIComponent(row.public_token)}`;}
function qrInto(el,url,size=180){el.innerHTML='';if(window.QRCode){new QRCode(el,{text:url,width:size,height:size,colorDark:'#050711',colorLight:'#ffffff',correctLevel:QRCode.CorrectLevel.M});}else el.textContent=url;}
function availableRewards(row){return rewards.filter(r=>{if(!r.activo)return false;if(r.condicion_tipo==='manual')return true;if(r.condicion_tipo==='sellos')return Number(row.sellos)>=Number(r.condicion_valor);if(r.condicion_tipo==='puntos')return Number(row.puntos)>=Number(r.condicion_valor);if(r.condicion_tipo==='cashback')return Number(row.cashback_saldo)>=Number(r.condicion_valor);return false;});}
function selectClient(id){selectedMembership=clients.find(x=>x.id===id)||null;renderClients();renderClientDetail();renderWalletClient();}
function renderClientDetail(){const host=$('#client-detail');const r=selectedMembership;if(!r){host.innerHTML='<div class="rw-empty">Selecciona un cliente.</div>';return;}const url=publicCardUrl(r);const ready=availableRewards(r);host.innerHTML=`<div class="rw-client-card"><p class="rw-kicker">TARJETA DEL CLIENTE</p><h3>${esc(r.rewards_clientes.nombre)}</h3><span class="meta">${esc(r.rewards_clientes.telefono||r.rewards_clientes.email||'Cliente Rewards')}</span><div class="rw-balance-grid"><div class="rw-balance"><small>Sellos</small><strong>${r.sellos}</strong></div><div class="rw-balance"><small>Puntos</small><strong>${num(r.puntos)}</strong></div><div class="rw-balance"><small>Cashback</small><strong>${money(r.cashback_saldo)}</strong></div></div><div id="selected-qr" class="rw-qr"></div><div class="rw-client-actions"><button class="rw-btn primary" id="register-purchase">+ Compra</button><a class="rw-btn" href="${esc(url)}" target="_blank" rel="noopener">Ver tarjeta</a><button class="rw-btn" id="copy-card">Copiar enlace</button><button class="rw-btn" id="open-wallet-tab">Wallet</button></div></div><div style="margin-top:14px"><h3>Recompensas ${ready.length?`<span class="rw-badge green">${ready.length} disponible(s)</span>`:''}</h3><div class="rw-list">${rewards.length?rewards.map(x=>{const isReady=ready.some(y=>y.id===x.id);return `<div class="rw-reward ${isReady?'available':''}"><h4>${esc(x.titulo)}</h4><p>${esc(x.descripcion||rewardConditionText(x))}</p>${isReady?`<button class="rw-btn green small" data-redeem="${x.id}" style="margin-top:9px">Canjear</button>`:`<span class="rw-badge" style="display:inline-flex;margin-top:9px">${esc(rewardConditionText(x))}</span>`}</div>`}).join(''):'<div class="rw-empty">No hay recompensas configuradas.</div>'}</div></div>`;setTimeout(()=>qrInto($('#selected-qr'),url,180),0);$('#register-purchase').onclick=()=>{ $('#purchase-client-name').textContent=r.rewards_clientes.nombre;$('#purchase-result').innerHTML='';$('#purchase-form').reset();openModal('#purchase-modal');};$('#copy-card').onclick=async()=>{await navigator.clipboard.writeText(url);toast('Enlace de tarjeta copiado.');};$('#open-wallet-tab').onclick=()=>activateTab('wallet');host.querySelectorAll('[data-redeem]').forEach(b=>b.onclick=()=>redeemReward(b.dataset.redeem));}

$('#purchase-form').addEventListener('submit',async e=>{e.preventDefault();if(!selectedMembership)return;const f=e.currentTarget,btn=f.querySelector('button[type=submit]'),fd=new FormData(f);btn.disabled=true;btn.textContent='Registrando…';const {data,error}=await supabase.rpc('rewards_registrar_compra',{p_membresia_id:selectedMembership.id,p_monto:Number(fd.get('monto')),p_referencia:fd.get('referencia')||null,p_nota:null});btn.disabled=false;btn.textContent='Confirmar compra';const out=$('#purchase-result');if(error){out.className='rw-result error';out.innerHTML=`<strong>No se registró</strong>${esc(error.message)}`;return;}out.className='rw-result';out.innerHTML=`<strong>Compra registrada ✓</strong>+${data.ganado.sellos} sellos · +${num(data.ganado.puntos)} puntos · +${money(data.ganado.cashback)} cashback${data.recompensas_disponibles?.length?`<br><b>🎁 ${data.recompensas_disponibles.length} recompensa(s) disponible(s)</b>`:''}`;await refreshAfterMovement(selectedMembership.id);toast('Compra registrada y saldos actualizados.');});
async function refreshAfterMovement(id){await Promise.all([loadClients(),loadSummary(),loadMovements()]);selectedMembership=clients.find(x=>x.id===id)||null;renderClients();renderClientDetail();renderWalletClient();}

async function loadRewards(){const {data,error}=await supabase.from('rewards_recompensas').select('*').eq('programa_id',program.id).order('orden');if(error)throw error;rewards=data||[];}
function rewardConditionText(r){if(r.condicion_tipo==='manual')return 'Disponible manualmente';if(r.condicion_tipo==='sellos')return `${num(r.condicion_valor)} sellos`;if(r.condicion_tipo==='puntos')return `${num(r.condicion_valor)} puntos`;return `${money(r.condicion_valor)} de cashback`;}
function renderRewards(){const host=$('#rewards-list');host.innerHTML=rewards.length?rewards.map(r=>`<div class="rw-list-item"><div class="rw-list-main"><strong>${esc(r.titulo)}</strong><small>${esc(r.descripcion||rewardConditionText(r))}</small></div><div class="rw-badges"><span class="rw-badge">${esc(rewardConditionText(r))}</span><button class="rw-btn danger small" data-disable-reward="${r.id}">${r.activo?'Desactivar':'Activar'}</button></div></div>`).join(''):'<div class="rw-empty">Crea tu primera recompensa.</div>';host.querySelectorAll('[data-disable-reward]').forEach(b=>b.onclick=async()=>{const r=rewards.find(x=>x.id===b.dataset.disableReward);const {error}=await supabase.from('rewards_recompensas').update({activo:!r.activo}).eq('id',r.id);if(error)return toast(error.message,'error');await loadRewards();renderRewards();if(selectedMembership)renderClientDetail();});}
$('#new-reward-btn').onclick=()=>openModal('#reward-modal');
$('#reward-form').addEventListener('submit',async e=>{e.preventDefault();const f=e.currentTarget,fd=new FormData(f),btn=f.querySelector('button');const type=fd.get('condicion_tipo');btn.disabled=true;btn.textContent='Creando…';const {error}=await supabase.from('rewards_recompensas').insert({programa_id:program.id,titulo:fd.get('titulo'),descripcion:fd.get('descripcion')||null,condicion_tipo:type,condicion_valor:type==='manual'?0:Number(fd.get('condicion_valor')||0),consume_saldo:fd.get('consume_saldo')==='on',premio_tipo:'beneficio',activo:true});btn.disabled=false;btn.textContent='Crear recompensa';if(error)return toast(error.message,'error');f.reset();f.consume_saldo.checked=true;closeModals();await loadRewards();renderRewards();if(selectedMembership)renderClientDetail();toast('Recompensa creada.');});
async function redeemReward(id){if(!selectedMembership)return;const r=rewards.find(x=>x.id===id);if(!confirm(`¿Canjear “${r?.titulo||'recompensa'}” para ${selectedMembership.rewards_clientes.nombre}?`))return;const {data,error}=await supabase.rpc('rewards_canjear_recompensa',{p_membresia_id:selectedMembership.id,p_recompensa_id:id,p_nota:'Canje desde panel Rewards'});if(error)return toast(error.message,'error');await refreshAfterMovement(selectedMembership.id);toast(`Recompensa canjeada: ${data.recompensa}`);}

async function loadMovements(){if(!program)return;const {data,error}=await supabase.from('rewards_movimientos').select('id,membresia_id,tipo,monto_compra,delta_puntos,delta_sellos,delta_cashback,referencia,nota,reversion_de,created_at,rewards_membresias(rewards_clientes(nombre))').eq('programa_id',program.id).order('created_at',{ascending:false}).limit(100);if(error){console.error(error);return;}movements=data||[];renderMovements();}
function renderMovements(){const host=$('#moves-list');if(!host)return;host.innerHTML=movements.length?movements.map(m=>{const name=m.rewards_membresias?.rewards_clientes?.nombre||'Cliente';const canReverse=m.tipo!=='reversion'&&!movements.some(x=>x.reversion_de===m.id);return `<div class="rw-movement"><div><strong>${esc(name)}</strong><br><small>${esc(fmtDate(m.created_at))}</small></div><div><strong>${esc(m.tipo.toUpperCase())}</strong><br><small>${m.monto_compra?money(m.monto_compra):esc(m.referencia||'')}</small></div><span class="${Number(m.delta_sellos)>=0?'rw-positive':'rw-negative'}">${Number(m.delta_sellos)>=0?'+':''}${m.delta_sellos} sello(s)</span><span class="${Number(m.delta_puntos)>=0?'rw-positive':'rw-negative'}">${Number(m.delta_puntos)>=0?'+':''}${num(m.delta_puntos)} pts</span><span class="${Number(m.delta_cashback)>=0?'rw-positive':'rw-negative'}">${Number(m.delta_cashback)>=0?'+':''}${money(m.delta_cashback)}</span><div>${canReverse?`<button class="rw-btn danger small" data-reverse="${m.id}">Revertir</button>`:''}</div></div>`}).join(''):'<div class="rw-empty">Los movimientos aparecerán aquí cuando registres compras o canjes.</div>';host.querySelectorAll('[data-reverse]').forEach(b=>b.onclick=()=>reverseMovement(b.dataset.reverse));}
$('#refresh-moves').onclick=loadMovements;
async function reverseMovement(id){const reason=prompt('Motivo de la reversión (queda en auditoría):');if(!reason)return;const row=movements.find(x=>x.id===id);const {error}=await supabase.rpc('rewards_revertir_movimiento',{p_movimiento_id:id,p_motivo:reason});if(error)return toast(error.message,'error');await refreshAfterMovement(row?.membresia_id||selectedMembership?.id);toast('Movimiento revertido sin borrar el historial.');}

function renderWalletClient(){const host=$('#wallet-client');const r=selectedMembership;$('#google-test').disabled=!r;$('#apple-test').disabled=!r;if(!r){host.innerHTML='<div class="rw-empty">Selecciona primero un cliente en la sección Clientes.</div>';return;}host.innerHTML=`<div class="rw-client-card"><h3>${esc(r.rewards_clientes.nombre)}</h3><span class="meta">${esc(program.nombre)}</span><div class="rw-balance-grid"><div class="rw-balance"><small>Sellos</small><strong>${r.sellos}</strong></div><div class="rw-balance"><small>Puntos</small><strong>${num(r.puntos)}</strong></div><div class="rw-balance"><small>Saldo</small><strong>${money(r.cashback_saldo)}</strong></div></div></div>`;}
async function walletCall(provider){if(!selectedMembership)return;const btn=provider==='google'?$('#google-test'):$('#apple-test');const old=btn.textContent;btn.disabled=true;btn.textContent='Preparando…';try{const res=await fetch(`${SUPABASE_URL}/functions/v1/rewards-wallet`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({provider,token:selectedMembership.public_token,origin:location.origin})});const type=res.headers.get('content-type')||'';if(provider==='apple'&&res.ok&&type.includes('application/vnd.apple.pkpass')){const blob=await res.blob();const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`${business.slug||'aliados'}-rewards.pkpass`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('Pase Apple Wallet generado.');return;}const data=await res.json().catch(()=>({message:'Respuesta inválida de Wallet'}));if(!res.ok)throw new Error(data.message||data.error||'No se pudo generar el pase');if(data.url){open(data.url,'_blank','noopener');toast('Abriendo Google Wallet…');}}catch(error){toast(error.message,'error',8000);}finally{btn.disabled=false;btn.textContent=old;}}
$('#google-test').onclick=()=>walletCall('google');$('#apple-test').onclick=()=>walletCall('apple');
async function checkWalletStatus(){try{const res=await fetch(`${SUPABASE_URL}/functions/v1/rewards-wallet`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'status'})});const data=await res.json();$('#google-status').textContent=data.google?.configured?'Integración configurada y lista para emitir pases.':'Motor listo; faltan credenciales de Google Wallet.';$('#apple-status').textContent=data.apple?.configured?'Integración configurada y lista para emitir pases.':'Motor listo; faltan certificado y Pass Type ID de Apple.';if(data.google?.configured&&data.apple?.configured)$('#wallet-credentials-note').textContent='Google Wallet y Apple Wallet están configurados para este entorno.';}catch{$('#google-status').textContent='Conector pendiente de desplegar.';$('#apple-status').textContent='Conector pendiente de desplegar.';}}

init().catch(error=>{console.error(error);toast(error.message||'No se pudo iniciar Rewards.','error',0);});
